apiVersion: v1
data:
  AdminPassword: <sanitized>
  AodhPassword: <sanitized>
  AodhDatabasePassword: <sanitized>
  BarbicanDatabasePassword: <sanitized>
  BarbicanPassword: <sanitized>
  BarbicanSimpleCryptoKEK: <sanitized>
  CeilometerPassword: <sanitized>
  CinderDatabasePassword: <sanitized>
  CinderPassword: <sanitized>
  DatabasePassword: <sanitized>
  DbRootPassword: <sanitized>
  DesignateDatabasePassword: <sanitized>
  DesignatePassword: <sanitized>
  GlanceDatabasePassword: <sanitized>
  GlancePassword: <sanitized>
  HeatAuthEncryptionKey: <sanitized>
  HeatDatabasePassword: <sanitized>
  HeatPassword: <sanitized>
  IronicDatabasePassword: <sanitized>
  IronicInspectorDatabasePassword: <sanitized>
  IronicInspectorPassword: <sanitized>
  IronicPassword: <sanitized>
  KeystoneDatabasePassword: <sanitized>
  ManilaDatabasePassword: <sanitized>
  ManilaPassword: <sanitized>
  MetadataSecret: <sanitized>
  NeutronDatabasePassword: <sanitized>
  NeutronPassword: <sanitized>
  NovaAPIDatabasePassword: <sanitized>
  NovaAPIMessageBusPassword: <sanitized>
  NovaCell0DatabasePassword: <sanitized>
  NovaCell0MessageBusPassword: <sanitized>
  NovaCell1DatabasePassword: <sanitized>
  NovaCell1MessageBusPassword: <sanitized>
  NovaPassword: <sanitized>
  OctaviaDatabasePassword: <sanitized>
  OctaviaPassword: <sanitized>
  PlacementDatabasePassword: <sanitized>
  PlacementPassword: <sanitized>
  SwiftPassword: <sanitized>
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
