apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Lab Network 172.20.133.0/24 VLAN1105 OVN Bridge
  name: vlan-1105-br-ex
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "br-ex-vlan1105",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-1105-br-ex",
      "vlanID": 1105
    }

